# Generated by Django 2.2.6 on 2020-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majority_report_app', '0002_auto_20200301_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviornment',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='enviornment',
            name='outcome',
        ),
        migrations.AddField(
            model_name='drive',
            name='accuracy',
            field=models.IntegerField(default=0, verbose_name='Accuracy:'),
        ),
        migrations.AddField(
            model_name='drive',
            name='outcome',
            field=models.CharField(default='', max_length=120, verbose_name='Outcome:'),
        ),
        migrations.AddField(
            model_name='enviornment',
            name='driver_dui2',
            field=models.CharField(choices=[(1, 'sober'), (2, 'intoxicated')], default='', max_length=120, verbose_name='Driver 2 Chemical Influence:'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='car1_prog',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Vehicle 1 Progress:'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='car1_turndist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Vehicle 1 Turn Distance:'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='car2_prog',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Vehicle 2 Progress:'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='car2_turndist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Vehicle 2 Turn Distance:'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='ghost_prog',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='AI Ghost Progress:'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='ghost_turndist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='AI Ghost Turn Distance:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='car1_spd',
            field=models.IntegerField(default=0, verbose_name='Vehicle 1 Speed:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='car2_spd',
            field=models.IntegerField(default=0, verbose_name='Vehicle 2 Speed:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='computer',
            field=models.CharField(choices=[(1, 'UNIVAC'), (2, 'Cray1'), (3, 'TRS'), (4, 'Commodore'), (5, 'Intel1'), (6, 'Intel2'), (7, 'AMD'), (8, 'Cray2'), (9, 'Intel3'), (10, 'Summit'), (11, 'Sycamore')], default='', max_length=120, verbose_name='AI Computer:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='distance',
            field=models.IntegerField(default=0, verbose_name='Distance:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_age1',
            field=models.CharField(choices=[(1, 'young'), (2, 'middle aged'), (3, 'old')], default='', max_length=120, verbose_name='Driver 1 Age:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_age2',
            field=models.CharField(choices=[(1, 'young'), (2, 'middle aged'), (3, 'old')], default='', max_length=120, verbose_name='Driver 2 Age:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_dui1',
            field=models.CharField(choices=[(1, 'sober'), (2, 'intoxicated')], default='', max_length=120, verbose_name='Driver 1 Chemical Influence:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_exp1',
            field=models.CharField(choices=[(1, 'experienced'), (2, 'inexperienced')], default='', max_length=120, verbose_name='Driver 1 Experience:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_exp2',
            field=models.CharField(choices=[(1, 'experienced'), (2, 'inexperienced')], default='', max_length=120, verbose_name='Driver 2 Experience:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_vision1',
            field=models.CharField(choices=[(1, 'near sighted'), (2, 'far sighted'), (3, 'normal')], default='', max_length=120, verbose_name='Driver 1 Vision:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_vision2',
            field=models.CharField(choices=[(1, 'near sighted'), (2, 'far sighted'), (3, 'normal')], default='', max_length=120, verbose_name='Driver 2 Vision:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='road_type',
            field=models.CharField(choices=[(1, 'dirt'), (2, 'gravel'), (3, 'asphalt')], default='', max_length=120, verbose_name='Road Type:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='road_width',
            field=models.IntegerField(default=0, verbose_name='Road Width:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='time',
            field=models.CharField(choices=[(1, 'morning'), (2, 'noon'), (3, 'evening'), (4, 'night')], default='', max_length=120, verbose_name='Time:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='vehicle1',
            field=models.CharField(choices=[(1, 'car'), (2, 'pickup'), (3, 'truck')], default='', max_length=120, verbose_name='Vehicle 1 Type:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='vehicle2',
            field=models.CharField(choices=[(1, 'car'), (2, 'pickup'), (3, 'truck')], default='', max_length=120, verbose_name='Vehicle 2 Type:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='weather',
            field=models.IntegerField(choices=[(1, 'clear'), (2, 'rain'), (3, 'snow'), (4, 'ice'), (5, 'fog'), (6, 'wind')], default=0, verbose_name='Weather:'),
        ),
    ]
