# Generated by Django 2.2.6 on 2020-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majority_report_app', '0003_auto_20200301_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='env',
            field=models.ForeignKey(on_delete=models.CASCADE, to='majority_report_app.Enviornment'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='computer',
            field=models.IntegerField(choices=[(1, 'UNIVAC 1 (1951)'), (2, 'Cray 1 (1975)'), (3, 'TRS-80 (1976)'), (4, 'Commodore 64 (1982)'), (5, 'Intel i386DX (1989)'), (6, 'Intel Pentium (1994)'), (7, 'AMD Athlon 64 3800+ X2 (2005)'), (8, 'Cray Titan (2012)'), (9, 'Intel Core i5 7300U (2016)'), (10, 'IBM Summit (2018)'), (11, 'Google Sycamore (2019)')], default=0, verbose_name='AI Computer:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_age1',
            field=models.IntegerField(choices=[(1, 'Young'), (2, 'Middle Aged'), (3, 'Old')], default=0, verbose_name='Driver 1 Age:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_age2',
            field=models.IntegerField(choices=[(1, 'Young'), (2, 'Middle Aged'), (3, 'Old')], default=0, verbose_name='Driver 2 Age:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_dui1',
            field=models.IntegerField(choices=[(1, 'Sober'), (2, 'Intoxicated')], default=0, verbose_name='Driver 1 Chemical Influence:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_dui2',
            field=models.IntegerField(choices=[(1, 'Sober'), (2, 'Intoxicated')], default=0, verbose_name='Driver 2 Chemical Influence:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_exp1',
            field=models.IntegerField(choices=[(1, 'Experienced'), (2, 'Inexperienced')], default=0, verbose_name='Driver 1 Experience:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_exp2',
            field=models.IntegerField(choices=[(1, 'Experienced'), (2, 'Inexperienced')], default=0, verbose_name='Driver 2 Experience:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_vision1',
            field=models.IntegerField(choices=[(1, 'Near Sighted'), (2, 'Far Sighted'), (3, 'Normal')], default=0, verbose_name='Driver 1 Vision:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='driver_vision2',
            field=models.IntegerField(choices=[(1, 'Near Sighted'), (2, 'Far Sighted'), (3, 'Normal')], default=0, verbose_name='Driver 2 Vision:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='road_type',
            field=models.IntegerField(choices=[(1, 'Dirt'), (2, 'Gravel'), (3, 'Asphalt')], default=0, verbose_name='Road Type:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='time',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Noon'), (3, 'Evening'), (4, 'Night')], default=0, verbose_name='Time:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='vehicle1',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Pickup'), (3, 'Truck')], default=0, verbose_name='Vehicle 1 Type:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='vehicle2',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Pickup'), (3, 'Truck')], default=0, verbose_name='Vehicle 2 Type:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='weather',
            field=models.IntegerField(choices=[(1, 'Clear'), (2, 'Rain'), (3, 'Snow'), (4, 'Ice'), (5, 'Fog'), (6, 'Wind')], default=0, verbose_name='Weather:'),
        ),
    ]
