# Generated by Django 2.2.6 on 2020-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majority_report_app', '0004_auto_20200307_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviornment',
            name='car1_spd',
            field=models.IntegerField(default=70, verbose_name='Vehicle 1 Speed:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='car2_spd',
            field=models.IntegerField(default=70, verbose_name='Vehicle 2 Speed:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='distance',
            field=models.IntegerField(default=1000, verbose_name='Distance:'),
        ),
        migrations.AlterField(
            model_name='enviornment',
            name='road_width',
            field=models.IntegerField(default=3, verbose_name='Road Width:'),
        ),
    ]
