# Generated by Django 2.2.6 on 2020-03-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majority_report_app', '0006_drive_iterations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='iterations',
        ),
    ]
